//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox.Website.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RobloxDefaultErrorPage_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RobloxDefaultErrorPage_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roblox.Website.App_LocalResources.RobloxDefaultErrorPage.aspx", typeof(RobloxDefaultErrorPage_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue to receive this page, please contact customer service at {0}..
        /// </summary>
        public static string CustomerServiceMessage {
            get {
                return ResourceManager.GetString("CustomerServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with your request..
        /// </summary>
        public static string Errors_400_Message {
            get {
                return ResourceManager.GetString("Errors.400.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string Errors_400_Title {
            get {
                return ResourceManager.GetString("Errors.400.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have permission to view this page!.
        /// </summary>
        public static string Errors_403_Message {
            get {
                return ResourceManager.GetString("Errors.403.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string Errors_403_Title {
            get {
                return ResourceManager.GetString("Errors.403.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have clicked an expired link or mistyped the address..
        /// </summary>
        public static string Errors_404_Message {
            get {
                return ResourceManager.GetString("Errors.404.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested page not found.
        /// </summary>
        public static string Errors_404_Title {
            get {
                return ResourceManager.GetString("Errors.404.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again after a few moments..
        /// </summary>
        public static string Errors_500_Message {
            get {
                return ResourceManager.GetString("Errors.500.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error with your request.
        /// </summary>
        public static string Errors_500_Title {
            get {
                return ResourceManager.GetString("Errors.500.Title", resourceCulture);
            }
        }
    }
}
